# Generated by Django 6.0.2 on 2026-03-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_id", models.CharField(max_length=100)),
                ("receiver_id", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("HIGH_RISK_ALERT", "High Risk Alert"),
                            ("DAILY_REMINDER", "Daily Reminder"),
                            ("APPOINTMENT", "Appointment"),
                            ("MESSAGE", "Message"),
                            ("GENERAL", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "related_patient_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "related_object_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("condition", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DISCHARGED", "Discharged"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="test123",
                        help_text="Patient login password (hashed in production)",
                        max_length=255,
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True, help_text="Weight in kilograms", null=True
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(
                        blank=True,
                        help_text="Baseline systolic BP (e.g., 120)",
                        null=True,
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(
                        blank=True,
                        help_text="Baseline diastolic BP (e.g., 80)",
                        null=True,
                    ),
                ),
                (
                    "blood_glucose_baseline",
                    models.IntegerField(
                        blank=True,
                        help_text="Baseline blood glucose in mg/dL",
                        null=True,
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, help_text="Comma-separated medical conditions"
                    ),
                ),
                (
                    "medications",
                    models.TextField(blank=True, help_text="Current medications"),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Known allergies"),
                ),
                (
                    "primary_provider_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_checkin", models.DateTimeField(blank=True, null=True)),
                (
                    "last_risk_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "last_risk_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("answers", models.JSONField(help_text="12 answers, each 0-3 scale")),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(
                        blank=True,
                        help_text="Patient's reading (if provided)",
                        null=True,
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(
                        blank=True,
                        help_text="Patient's reading (if provided)",
                        null=True,
                    ),
                ),
                (
                    "blood_glucose_reading",
                    models.IntegerField(
                        blank=True,
                        help_text="Patient's reading (if provided)",
                        null=True,
                    ),
                ),
                ("risk_level", models.CharField(max_length=20)),
                ("risk_color", models.CharField(max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=100)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=100, unique=True)),
                ("specialty", models.CharField(blank=True, max_length=100)),
                ("hospital", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("chat_partner_id", models.CharField(max_length=100)),
                ("is_typing", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "chat_partner_id"],
                        name="api_typings_user_id_88af08_idx",
                    )
                ],
                "unique_together": {("user_id", "chat_partner_id")},
            },
        ),
    ]
