# Generated by Django 6.0.2 on 2026-02-27 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=100, unique=True)),
                ("condition", models.CharField(max_length=50)),
                ("last_checkin", models.DateTimeField(blank=True, null=True)),
                (
                    "last_risk_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "last_risk_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("answers", models.JSONField()),
                ("risk_level", models.CharField(max_length=20)),
                ("risk_color", models.CharField(max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
