# Generated by Django 6.0.4 on 2026-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="initiated_by",
            field=models.CharField(
                choices=[("PATIENT", "Patient"), ("PROVIDER", "Provider")],
                default="PATIENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("SCHEDULED", "Scheduled"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
