# Generated by Django 6.0.4 on 2026-05-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_appointment_pending_initiated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="home_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="id_number",
            field=models.CharField(
                blank=True, help_text="National ID number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="patient",
            name="pin",
            field=models.CharField(
                blank=True,
                help_text="Patient PIN for phone+PIN login (plain-text; hash in production)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="surname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="patient",
            name="password",
            field=models.CharField(
                default="test123", help_text="Legacy password field", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="ClinicalVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hcw_id",
                    models.CharField(
                        help_text="provider_id of the HCW who recorded this visit",
                        max_length=100,
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                ("diastolic_bp", models.IntegerField(blank=True, null=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                (
                    "blood_glucose",
                    models.IntegerField(blank=True, help_text="mg/dL", null=True),
                ),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                (
                    "temperature",
                    models.FloatField(blank=True, help_text="Celsius", null=True),
                ),
                (
                    "oxygen_saturation",
                    models.FloatField(blank=True, help_text="SpO2 %", null=True),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "medication_intake",
                    models.TextField(
                        blank=True, help_text="Medications taken at this visit"
                    ),
                ),
                (
                    "changes_made",
                    models.TextField(
                        blank=True, help_text="Any changes to treatment/medication"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_visits",
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
    ]
