# Generated by Django 6.0.2 on 2026-05-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_district_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalvisit',
            name='appointment',
            field=models.OneToOneField(blank=True, help_text='The appointment this visit was auto-created from (null for walk-ins/emergencies)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_visit', to='api.appointment'),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='previous_data_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of last check-in vitals + baseline at appointment approval time for comparison', null=True),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='visit_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Scheduled Appointment'), ('EMERGENCY', 'Emergency Visit'), ('OTHER', 'Other')], default='APPOINTMENT', max_length=20),
        ),
    ]
