# Generated by Django 6.0.2 on 2026-03-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_create_default_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("chat_partner_id", models.CharField(max_length=100)),
                ("is_typing", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "chat_partner_id"],
                        name="api_typings_user_id_88af08_idx",
                    )
                ],
                "unique_together": {("user_id", "chat_partner_id")},
            },
        ),
    ]
