# Generated by Django 6.0.2 on 2026-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clinicalvisit_appointment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalvisit',
            name='egfr',
            field=models.FloatField(blank=True, help_text='eGFR ml/min/1.73m^2 (Diabetes)', null=True),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='hba1c',
            field=models.FloatField(blank=True, help_text='HbA1c % (Diabetes)', null=True),
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='bpm (Cardiovascular)', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalvisit',
            name='blood_glucose',
            field=models.IntegerField(blank=True, help_text='mg/dL (generic/baseline)', null=True),
        ),
    ]
